name: Check formatting with rustfmt
run-name: Ensure rustfmt check passes
on: [push]
jobs:
  Check-Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rustfmt
        run: sudo apt-get update && sudo apt-get install -y rustfmt
      - name: Check vpn-types subcrate
        run: rustfmt --edition 2021 --check $GITHUB_WORKSPACE/types/src/lib.rs
      - name: Check vpn-operator subcrate
        run: rustfmt --edition 2021 --check $GITHUB_WORKSPACE/operator/src/main.rs
