name: Check formatting with rustfmt
run-name: Ensure rustfmt check passes
on: [push]
jobs:
  Check-Formatting:
    runs-on: ubuntu-latest
    steps:
      - run: apt update && apt install -y rustfmt
      - name: vpn-types subcrate
        run: rustfmt --edition 2021 --check types/src/lib.rs
      - name: vpn-operator subcrate
        run: rustfmt --edition 2021 --check operator/src/main.rs
