name: Check formatting with rustfmt
run-name: Ensure rustfmt check passes
on: [push]
jobs:
  Check-Formatting:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y rustfmt
      - run: ls -al $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE && find .
      - name: vpn-types subcrate
        run: rustfmt --edition 2021 --check $GITHUB_WORKSPACE/types/src/lib.rs
      - name: vpn-operator subcrate
        run: rustfmt --edition 2021 --check $GITHUB_WORKSPACE/operator/src/main.rs
